### ISSUE TITLE
touch screen has no effect

### ISSUE THREAD

**Issue by 1548976092** [Azkali/GPD-P2-MAX-Hackintosh#20]
After I use this version of efi, the touch screen has no effect. Can you take a video and show me your performance?

**Comment by Azkali** [comment]
Are you using Mojave ? I"m gonna update the README file but the driver doesn't work on Mojave.

Otherwise if you are on Catalina, can you share your original `DSDT.aml` file.
On clover boot screen before selecting MacOS press F4, then after booting into MacOS mount your EFI partition and go into `ACPI/origin` you'll find the `DSDT.aml` file.

**Comment by bertiepeek** [comment]
Hi, I'm having the same issue using the latest EFI folder on 0.24 BIOS with up-to-date Catalina. No response from touch screen. DSDT.aml file attached - 
[DSDT.aml.zip](https://github.com/Azkali/GPD-P2-MAX-Hackintosh/files/4099515/DSDT.aml.zip)

**Comment by 1548976092** [comment]
I'm very interested in touch screen, could you please take a short video upload yutube and give me a link?

**Comment by Azkali** [comment]
@bertiepeek did you use the `DSDT.aml` file because this is the one you need not the `DSDT_2.aml` ( you have a 1st batch P2 Max ) ?

**Comment by bertiepeek** [comment]
> @bertiepeek did you use the `DSDT.aml` file because this is the one you need not the `DSDT_2.aml` ( you have a 1st batch P2 Max ) ?

Yes I tried both in fact!

**Comment by Azkali** [comment]
Oh I see why my repository isn't properly working, so basically I'm an idiot .. I'm gonna fix that quickly
